##MESSAGE#
version: "{COMPOSE_FILE_VERSION}"

services:
  db:
    image: postgres:13
    user: root
    tty: true
    ports:
      - {POSTGRES_PORT}:{POSTGRES_DOCKER_PORT}
    environment:
      - POSTGRES_PASSWORD={POSTGRES_ODOO_PASS}
      - POSTGRES_USER={POSTGRES_ODOO_USER}
      - POSTGRES_DB=postgres

  odoo:
    image: {ODOO_IMAGE}
    user: {CURRENT_USER}
    tty: true
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - {ODOO_PORT}:{ODOO_DOCKER_PORT}
      - {DEBUGGER_PORT}:{DEBUGGER_DOCKER_PORT}

    volumes: {MAPPED_VOLUMES}

    command: {START_STRING}
